<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUsers($customer)
	{
		$query = $this->createQueryBuilder('u')
			->where('u.customer = :customer')
			->setParameter('customer', $customer)
			->orderBy('u.username', 'DESC')
			->getQuery();

			return $query->getResult();
	}
}
